### ISSUE TITLE
Minecraft server sometimes fails to start during scheduled restart

### ISSUE THREAD

**Issue by jivanpal** [Osiris-Team/AutoPlug-Client#230]
<details>
  <summary>Show log</summary>
  
```log
[27-02-2024 05:00:00][AP][INFO] Executing scheduled restart in 10sec(s)...
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:00 INFO]: [Not Secure] [Server] Restarting in 10 seconds.
[05:00:00 INFO]: [Not Secure] [Server] Please allow up to 2min for this process to complete.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:07 INFO]: [Not Secure] [Server] Restarting in 3.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:08 INFO]: [Not Secure] [Server] Restarting in 2.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:09 INFO]: [Not Secure] [Server] Restarting in 1.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:10 INFO]: [Not Secure] [Server] Restarting...
[27-02-2024 05:00:11][AP][INFO] Restarting server...
[27-02-2024 05:00:11][AP][INFO] Stopping server...
[05:00:11 INFO]: Stopping the server
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[27-02-2024 05:00:11][AP][WARN] Broken pipe
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Stopping server
[05:00:11 INFO]: [SkinsRestorer] Disabling SkinsRestorer v15.0.7
[05:00:11 INFO]: [OpeNLogin] Disabling OpeNLogin v1.6.5
[05:00:11 INFO]: Saving players
[05:00:11 INFO]: Saving worlds
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Saved 3 block chunks, 102 entity chunks, 0 poi chunks in world 'world' in 0.09s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Saved 3 block chunks, 64 entity chunks, 0 poi chunks in world 'world_nether' in 0.05s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Saved 1 block chunks, 45 entity chunks, 0 poi chunks in world 'world_the_end' in 0.03s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:00:11 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[05:00:11 INFO]: Flushing Chunk IO
[05:00:11 INFO]: Closing Thread Pool
[05:00:11 INFO]: Closing Server
[27-02-2024 05:00:13][AP][INFO] Server was stopped.
[27-02-2024 05:00:13][AP][INFO] To stop AutoPlug too, enter '.stop both'.
[28-02-2024 05:00:00][AP][WARN] Error while executing restart! Details: Server is not running. Restart not possible.
```
</details>

**Expected**
Minecraft server should start normally after it is stopped during a scheduled restart.

**Actual**
Some exceptions are thrown by `SmartString.toString()`, seemingly causing the server to crash, after which AutoPlug reports: "Server is not running. Restart not possible." The exceptions seem to be thrown during every scheduled restart, but the failure to actually restart the server only occurs sometimes. For example, here are the logs from the previous scheduled restart, in which the exceptions were thrown but the restart was successful:

<details>
  <summary>Show log</summary>

```log
[26-02-2024 05:00:00][AP][INFO] Executing scheduled restart in 10sec(s)...
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:00 INFO]: [Not Secure] [Server] Restarting in 10 seconds.
[05:00:00 INFO]: [Not Secure] [Server] Please allow up to 2min for this process to complete.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:07 INFO]: [Not Secure] [Server] Restarting in 3.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:08 INFO]: [Not Secure] [Server] Restarting in 2.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:09 INFO]: [Not Secure] [Server] Restarting in 1.
java.lang.Exception
        at com.osiris.dyml.SmartString.toString(SmartString.java:39)
        at java.base/java.lang.String.valueOf(String.java:4220)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
        at com.osiris.autoplug.client.tasks.scheduler.RestartJob.execute(RestartJob.java:54)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[05:00:10 INFO]: [Not Secure] [Server] Restarting...
[26-02-2024 05:00:11][AP][INFO] Restarting server...
[26-02-2024 05:00:11][AP][INFO] Stopping server...
[05:00:11 INFO]: Stopping the server
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Unknown command. Type "/help" for help.
[05:00:11 INFO]: Stopping server
[05:00:11 INFO]: [SkinsRestorer] Disabling SkinsRestorer v15.0.7
[05:00:11 INFO]: [OpeNLogin] Disabling OpeNLogin v1.6.5
[05:00:11 INFO]: Saving players
[05:00:11 INFO]: Saving worlds
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[05:00:11 INFO]: [ChunkHolderManager] Saved 4 block chunks, 116 entity chunks, 0 poi chunks in world 'world' in 0.08s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[05:00:11 INFO]: [ChunkHolderManager] Saved 3 block chunks, 62 entity chunks, 0 poi chunks in world 'world_nether' in 0.06s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:00:11 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[05:00:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[05:00:11 INFO]: [ChunkHolderManager] Saved 1 block chunks, 46 entity chunks, 0 poi chunks in world 'world_the_end' in 0.02s
[05:00:11 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:00:11 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[05:00:11 INFO]: Flushing Chunk IO
[05:00:11 INFO]: Closing Thread Pool
2024-02-26 05:00:11,534 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[05:00:11 INFO]: Closing Server
[26-02-2024 05:00:12][AP][INFO] Running pre-startup tasks, please be patient...
[26-02-2024 05:00:12][AP][INFO] [TASK] [\] > [SelfUpdater] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [|] > [BackupTask] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [/] > [GeneralTasks] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [-] > [DailyRestarter] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [\] > [CustomRestarter] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [|] > [JavaUpdater] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [/] > [ServerUpdater] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [-] > [PluginsUpdater] Initialising...
[26-02-2024 05:00:12][AP][INFO] [TASK] [\] > [ModsUpdater] Initialising...
[26-02-2024 05:00:12][AP][INFO]
[26-02-2024 05:00:12][AP][INFO] Server was stopped.
[26-02-2024 05:00:12][AP][INFO] To stop AutoPlug too, enter '.stop both'.
[26-02-2024 05:00:17][AP][INFO] [TASK] [#] > [SelfUpdater][100%] AutoPlug is on the latest version!
[26-02-2024 05:00:17][AP][INFO] [TASK] [|] > [BackupTask] Backing up /opt/minecraft-instances/2/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar 0% - ADD_ENTRY
[26-02-2024 05:00:17][AP][INFO] [TASK] [/] > [GeneralTasks] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [-] > [DailyRestarter] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [\] > [CustomRestarter] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [|] > [JavaUpdater] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [/] > [ServerUpdater] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [-] > [PluginsUpdater] Initialising...
[26-02-2024 05:00:17][AP][INFO] [TASK] [\] > [ModsUpdater] Initialising...

...

[26-02-2024 05:01:39][AP][INFO]
[26-02-2024 05:01:39][AP][INFO] GeneralTasks:
[26-02-2024 05:01:39][AP][INFO] Directory cleaner removed 6 files, from directory ./autoplug/logs
[26-02-2024 05:01:39][AP][INFO] Directory cleaner removed 1 files, from directory ./autoplug/downloads
[26-02-2024 05:01:39][AP][INFO] ServerUpdater:
[26-02-2024 05:01:39][AP][WARN] No further information available!
[26-02-2024 05:01:39][AP][INFO] PluginsUpdater:
[26-02-2024 05:01:39][AP][WARN] This server is either not registered or not premium, thus failed to fill in missing plugin details via the AutoPlug-Web database. Disable [updater, plugins-updater, web-database, enable] in the /autop
lug/updater.yml to hide this warning.
[26-02-2024 05:01:39][AP][INFO] ModsUpdater:
[26-02-2024 05:01:39][AP][WARN] No mods found in ./mods! Nothing to check...
[26-02-2024 05:01:39][AP][INFO] PluginDownloader:
[26-02-2024 05:01:39][AP][WARN] Download of 'OpeNLogin-[7.5.10].jar' failed because of invalid content type: text
[26-02-2024 05:01:39][AP][INFO] Starting server: server.jar
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [SelfUpdater][100%] AutoPlug is on the latest version!
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [BackupTask][100%] Completed backup & skipped upload.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [GeneralTasks][100%] Finished.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [DailyRestarter][100%] Restarts at: [5:0]
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [CustomRestarter] Skipped.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [JavaUpdater] Skipped.
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [ServerUpdater][100%] Initialising...
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [PluginsUpdater][100%] Checked 2/2 plugins.
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [ModsUpdater][100%] No mods found in ./mods! Nothing to check...
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [PluginDownloader][100%] Download of 'OpeNLogin-[7.5.10].jar' failed because of invalid content type: text
[26-02-2024 05:01:42][AP][INFO]
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [SelfUpdater][100%] AutoPlug is on the latest version!
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [BackupTask][100%] Completed backup & skipped upload.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [GeneralTasks][100%] Finished.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [DailyRestarter][100%] Restarts at: [5:0]
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [CustomRestarter] Skipped.
[26-02-2024 05:01:42][AP][INFO] [TASK] [#] > [JavaUpdater] Skipped.
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [ServerUpdater][100%] Initialising...
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [PluginsUpdater][100%] Checked 2/2 plugins.
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [ModsUpdater][100%] No mods found in ./mods! Nothing to check...
[26-02-2024 05:01:42][AP][INFO] [TASK] [1] > [PluginDownloader][100%] Download of 'OpeNLogin-[7.5.10].jar' failed because of invalid content type: text
[26-02-2024 05:01:42][AP][INFO]
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.10+7-Debian-1deb12u1) Host: Linux 6.1.0-18-amd64 (amd64)
Loading libraries, please wait...
```

</details>

**Steps**
N/A.

Autoplug restarter (`autoplug/restarter.yml`) is configured with the defaults:

```yaml
restarter:
  daily-restarter:
    enable: true
    times: 05:00
    commands:
      list:
        10:
          - say Restarting in 10 seconds.
          - say Please allow up to 2min for this process to complete.
        3: say Restarting in 3.
        2: say Restarting in 2.
        1: say Restarting in 1.
        0: say Restarting...
  custom-restarter:
    enable: false
```

AutoPlug "restart on crash" is enabled in `autoplug/general.yml`:

```yaml
general:
  autoplug:
    target-software: MINECRAFT_SERVER
    start-on-boot: true
    system-tray:
      enable: false
      theme: light
    auto-stop: false
  server:
    start-command: java -Xms512M -Xmx7680M -XX:+UseG1GC -jar server.jar nogui
    auto-start: true
    restart-on-crash: true
```

**Screenshots**
N/A

**Comment by Osiris-Team** [comment]
Possible fix in 7.5.13
