### ISSUE TITLE
IOException when losing connection!

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/AutoPlug-Client#51]
**Describe the bug**
After losing connection to AutoPlug-Web this happens.

**Error-Message:**
```log
[20-05-2021 19:53:40][AutoPlug][WARN] ================================
[20-05-2021 19:53:40][AutoPlug][WARN] Message: Lost connection to AutoPlug-Web! Reconnecting in 30 seconds...
[20-05-2021 19:53:40][AutoPlug][WARN] Details: null
[20-05-2021 19:53:40][AutoPlug][WARN] Type: java.io.EOFException
[20-05-2021 19:53:40][AutoPlug][WARN] Stacktrace: 
[20-05-2021 19:53:40][AutoPlug][WARN] java.base/java.io.DataInputStream.readBoolean(DataInputStream.java:248)
[20-05-2021 19:53:40][AutoPlug][WARN] com.osiris.autoplug.client.network.online.MainConnection.run(MainConnection.java:74)
[20-05-2021 19:53:40][AutoPlug][WARN] ================================
java.io.IOException: Write end dead
        at java.base/java.io.PipedInputStream.read(PipedInputStream.java:310)
        at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at com.osiris.autoplug.client.utils.NonBlockingPipedInputStream.lambda$new$1(NonBlockingPipedInputStream.java:27)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Osiris-Team** [comment]
Since the changes related to that have been reverted, that error shouldn't happen anymore...
Currently im still not sure how to proceed though,
thats why this issue stays opened
