### ISSUE TITLE
Main jar corrupts when automatically updating (only when using screen)

### ISSUE THREAD

**Issue by DannyDorito24** [Osiris-Team/AutoPlug-Client#75]
When using the built in automatic updating for AutoPlug, the main jarfile will usually corrupt itself upon trying to update. This may be something that only happens on my system, I'm not sure. I am running Ubuntu Server version 21.04. The logs have no good information to go off of, at least for me. 

Here are some relevant lines from the log, but they seem unhelpful. It just stops.
```
[11-07-2021 04:02:48][AP][DEBUG][TaskServerDownload] Downloading AutoPlug-Client.jar from: https://github.com/Osiris-Team/AutoPlug-Releases/raw/master/stable-builds/AutoPlug-Client.jar
[11-07-2021 04:02:50][AP][DEBUG][TaskServerDownload] Comparing hashes (SHA-256):
[11-07-2021 04:02:50][AP][DEBUG][TaskServerDownload] Input-Hash: 74f5a3adcc283a9293b3d3b37899d2d2f43b33147e228b2fd320d9f116397cbe
[11-07-2021 04:02:50][AP][DEBUG][TaskServerDownload] File-Hash: 74f5a3adcc283a9293b3d3b37899d2d2f43b33147e228b2fd320d9f116397cbe
[11-07-2021 04:02:50][AP][INFO] See you soon!
[11-07-2021 04:02:50][AP][DEBUG][AL] Stopped AP
```

After this happens, the server becomes unusable, with java simply returning, "Error: Invalid or corrupt jarfile AutoPlug-Client.jar"

I would imagine this may be something I'm doing wrong, and I'll edit and upload logs if you need them but I'd rather not since they contain possibly sensitive information.

**Comment by nathanfusselman** [comment]
I can agree that this does happen. I do not have a lot to go with this but it happens seemingly every time there is an update. I am using pterodactyl and that is a smaller use case so this may be related to only linux use or maybe even just docker and pterodactyl but not sure. You are welcome to use my pterodactyl server where I can setup a test server for you to use if you need. (I just updated to the beta and can let you know if it happens again, I will just leave it enabled on one server)

**Comment by Osiris-Team** [comment]
@DannyDorito24 from which version did you update?
I just tested the self updater on Ubuntu and Windows by myself and it works. (I fixed the self-updater in v2.4, if u were updating from a version below that, the error you get would be explained)
There is another exception at the, but not something that causes the jar to corrupt.
Here is my console output:
```log
Initialising AutoPlug-Client - 2.0
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO]      ___       __       ___  __             
[21:37][AP][INFO]     / _ |__ __/ /____  / _ \/ /_ _____ _   
[21:37][AP][INFO]    / __ / // / __/ _ \/ ___/ / // / _ `/   
[21:37][AP][INFO]   /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
[21:37][AP][INFO]                                  /___/    
[21:37][AP][INFO] 
[21:37][AP][INFO] Version: AutoPlug-Client - 2.0
[21:37][AP][INFO] Author: Osiris Team
[21:37][AP][INFO] Web-Panel: https://autoplug.online/
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO] Loading configurations...
[21:37][AP][INFO] Configurations loaded.
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO] Authenticating server...
[21:37][AP][WARN] Connection issues! Details: [CON_TYPE: 0] Authentication failed (code:1): No matching server key found! Register your server at https://autoplug.online/ and get your server-key. Restart AutoPlug when done.
[21:37:12][AP][TASK] [\] > [Self-Updater] Update found (2.0 -> 3.0), started download!
[21:37:12][AP][TASK] [\] > [ServerFilesBackup] Initialising...                                  
[21:37:12][AP][TASK] [\] > [WorldsBackup] Initialising...                                        
[21:37:12][AP][TASK] [\] > [PluginsBackup] Initialising...                                       
[21:37:12][AP][TASK] [\] > [DailyRestarter] Initialising...                                      
[21:37:12][AP][TASK] [\] > [CustomRestarter] Initialising...                                     
[21:37:12][AP][TASK] [\] > [JavaUpdater] Initialising...                                         
[21:37:12][AP][TASK] [\] > [ServerUpdater] Initialising...                                       
[21:37:12][AP][TASK] [\] > [PluginsUpdater] Initialising...                                      
[21:37:12][AP][TASK] [#] > [Downloader][100%] Downloaded AutoPlug-Client.jar (8mb/8mb)
Initialising AutoPlug-Client - 3.0
osiris@ubuntu-mini:~/Desktop/my server$  + Created directory: plugins
 + Created directory: autoplug-downloads
 + Created directory: autoplug-backups
 + Created directory: server
 + Created directory: plugins
 + Created directory: worlds
 + Created directory: autoplug-logs
 + Created directory: autoplug-system
[21:37][AP][INFO] Found: /home/osiris/Desktop/my server/AutoPlug-Client.jar
[21:37][AP][INFO] Found: /home/osiris/Desktop/my server/autoplug-downloads/AutoPlug-Client-Copy.jar
[21:37][AP][INFO] Installing update...
[21:37][AP][INFO] Success!
[21:37][AP][INFO] Starting jar with: [/usr/lib/jvm/java-11-openjdk-amd64/bin/java, -jar, /home/osiris/Desktop/my server/AutoPlug-Client.jar]
[21:37][AP][INFO] See you soon!

Initialising AutoPlug-Client - 3.0
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO]      ___       __       ___  __             
[21:37][AP][INFO]     / _ |__ __/ /____  / _ \/ /_ _____ _   
[21:37][AP][INFO]    / __ / // / __/ _ \/ ___/ / // / _ `/   
[21:37][AP][INFO]   /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
[21:37][AP][INFO]                                  /___/    
[21:37][AP][INFO] 
[21:37][AP][INFO] Version: AutoPlug-Client - 3.0
[21:37][AP][INFO] Author: Osiris Team
[21:37][AP][INFO] Web-Panel: https://autoplug.online/
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO] Loading configurations...
[21:37][AP][INFO] Configurations loaded.
[21:37][AP][INFO] | ------------------------------------------- |
[21:37][AP][INFO] Authenticating server...

Exception in thread "InputListenerThread" java.io.IOError: java.io.IOException: Input/output error
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:446)
	at com.osiris.autoplug.client.console.UserInput.lambda$keyboard$0(UserInput.java:39)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Input/output error
	at java.base/java.io.FileInputStream.read0(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:231)
	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73)
	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62)
	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168)
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
	... 8 more

```
This is how I am testing the self-updater:
1. Open the AutoPlug-Client.jar and modify the autoplug.properties files version to something lower
2. Make sure that self updater is enabled and set to automatic (stable builds are selected)
3. Run AutoPlug

**Comment by DannyDorito24** [comment]
@Osiris-Team I was updating from version 2.9, and I'm using a paperMC server. I can reliably reproduce this issue on my server with an older jar. I'm running it in a screen session because it's a remote machine. Could this be the issue somehow?

Also I'm not entirely sure what you mean by "Open the AutoPlug-Client.jar and modify the autoplug.properties files version to something lower"

**Comment by Osiris-Team** [comment]
@DannyDorito24 ok great! Could you reproduce it and then attach the console log, like I did.
And what I meant was opening the AutoPlug-Client.jar with 7zip or winrar then open the autoplug.properties file inside it and change the version. That file holds some details regarding the jar.

**Comment by DannyDorito24** [comment]
Okay, out of curiosity I tried it outside of a screen session and it works fine. I'm not sure why it doesn't work but I'm pretty sure that's the issue.

(Also editing the files seems to corrupt the jar on a Mac, weird)

**Comment by DannyDorito24** [comment]
This is all I get from a log within a screen session.

```
[11-07-2021 18:45:38][AP][DEBUG][AL] Started Logger(AP)
[11-07-2021 18:45:38][AP][DEBUG][Main] !!!IMPORTANT!!! -> THIS LOG-FILE CONTAINS SENSITIVE INFORMATION <- !!!IMPORTANT!!!
[11-07-2021 18:45:38][AP][DEBUG][Main] !!!IMPORTANT!!! -> THIS LOG-FILE CONTAINS SENSITIVE INFORMATION <- !!!IMPORTANT!!!
[11-07-2021 18:45:38][AP][DEBUG][Main] !!!IMPORTANT!!! -> THIS LOG-FILE CONTAINS SENSITIVE INFORMATION <- !!!IMPORTANT!!!
[11-07-2021 18:45:38][AP][INFO] | ------------------------------------------- |
[11-07-2021 18:45:38][AP][INFO]      ___       __       ___  __             
[11-07-2021 18:45:38][AP][INFO]     / _ |__ __/ /____  / _ \/ /_ _____ _   
[11-07-2021 18:45:38][AP][INFO]    / __ / // / __/ _ \/ ___/ / // / _ `/   
[11-07-2021 18:45:38][AP][INFO]   /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
[11-07-2021 18:45:38][AP][INFO]                                  /___/    
[11-07-2021 18:45:38][AP][INFO] 
[11-07-2021 18:45:38][AP][INFO] Version: AutoPlug-Client - 2.9
[11-07-2021 18:45:38][AP][INFO] Author: Osiris Team
[11-07-2021 18:45:38][AP][INFO] Web-Panel: https://autoplug.online/
[11-07-2021 18:45:38][AP][INFO] | ------------------------------------------- |
[11-07-2021 18:45:38][AP][INFO] Loading configurations...
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, key] VAL: [] DEF: [INSERT_KEY_HERE]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, auto-start] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, autoplug-stop] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, stop-command] VAL: [] DEF: [stop]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, java-version] VAL: [] DEF: [java]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, jar] VAL: [] DEF: [auto-find]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, flags, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, flags, list] VAL: [] DEF: [Xms2G, Xmx2G]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, arguments, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-general-config, server, arguments, list] VAL: [] DEF: [--nogui]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-logger-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-logger-config, debug] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-logger-config, autoplug-label] VAL: [] DEF: [AP]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-logger-config, force-ANSI] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config, online-console, send] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config, online-console, receive] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config, updater-results, send-plugins-updaters-results] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config, updater-results, send-server-updaters-results] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-web-config, updater-results, send-self-updaters-results] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, max-days] VAL: [] DEF: [7]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, cool-down] VAL: [] DEF: [60]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, exclude, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, exclude, list] VAL: [] DEF: [./example/directory, ./specific-file.txt, C:\Users\Example Windows Directory]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, include, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, include, list] VAL: [] DEF: [./example/directory, ./specific-file.txt, C:\Users\Example Windows Directory]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, delete-on-complete] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, host] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, port] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, username] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, password] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, path] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, server-files-backup, upload, rsa-key] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, max-days] VAL: [] DEF: [7]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, cool-down] VAL: [] DEF: [60]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, exclude, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, exclude, list] VAL: [] DEF: [./example/directory, ./specific-file.txt, C:\Users\Example Windows Directory]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, include, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, include, list] VAL: [] DEF: [./example/directory, ./specific-file.txt, C:\Users\Example Windows Directory]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, delete-on-complete] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, host] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, port] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, username] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, password] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, path] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, worlds-backup, upload, rsa-key] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, max-days] VAL: [] DEF: [7]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, cool-down] VAL: [] DEF: [60]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, exclude, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, exclude, list] VAL: [] DEF: [./plugins/dynmap, ./plugins/WorldBorder]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, include, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, include, list] VAL: [] DEF: [./example/directory, ./specific-file.txt, C:\Users\Example Windows Directory]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, delete-on-complete] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, host] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, port] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, username] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, password] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, path] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-backup-config, plugins-backup, upload, rsa-key] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, times] VAL: [] DEF: [23:00, 11:00]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list, 10] VAL: [] DEF: [say [Server] Server is restarting in 10 seconds., say [Server] Please allow up to 2min for this process to complete.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list, 3] VAL: [] DEF: [say [Server] Server is restarting in 3.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list, 2] VAL: [] DEF: [say [Server] Server is restarting in 2.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list, 1] VAL: [] DEF: [say [Server] Server is restarting in 1.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, daily-restarter, commands, list, 0] VAL: [] DEF: [say [Server] Server is restarting...]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, cron] VAL: [] DEF: [0 30 9 * * ? *]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list, 10] VAL: [] DEF: [say [Server] Server is restarting in 10 seconds., say [Server] Please allow up to 2min for this process to complete.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list, 3] VAL: [] DEF: [say [Server] Server is restarting in 3.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list, 2] VAL: [] DEF: [say [Server] Server is restarting in 2.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list, 1] VAL: [] DEF: [say [Server] Server is restarting in 1.]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-restarter-config, custom-restarter, commands, list, 0] VAL: [] DEF: [say [Server] Server is restarting...]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, self-updater, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, self-updater, profile] VAL: [] DEF: [AUTOMATIC]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, self-updater, build] VAL: [] DEF: [stable]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, server-updater, enable] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, server-updater, profile] VAL: [] DEF: [MANUAL]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, server-updater, software] VAL: [] DEF: [paper]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, server-updater, version] VAL: [] DEF: [1.16.4]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, server-updater, build-id] VAL: [] DEF: [0]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, plugins-updater, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, plugins-updater, profile] VAL: [] DEF: [MANUAL]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-updater-config, plugins-updater, async] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-tasks-config] VAL: [] DEF: []
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-tasks-config, live-tasks, enable] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-tasks-config, live-tasks, refresh-interval] VAL: [] DEF: [250]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-tasks-config, show-warnings] VAL: [] DEF: [true]
[11-07-2021 18:45:38][AP][DEBUG][ConfigUtils] [autoplug-tasks-config, show-detailed-warnings] VAL: [] DEF: [false]
[11-07-2021 18:45:38][AP][INFO] Configurations loaded.
[11-07-2021 18:45:38][AP][DEBUG][Main]  
[11-07-2021 18:45:38][AP][DEBUG][Main] DEBUG DETAILS:
[11-07-2021 18:45:38][AP][DEBUG][Main] SYSTEM OS: Mac OS X
[11-07-2021 18:45:38][AP][DEBUG][Main] SYSTEM VERSION: 11.4
[11-07-2021 18:45:38][AP][DEBUG][Main] JAVA VERSION: 16.0.1
[11-07-2021 18:45:38][AP][DEBUG][Main] JAVA VENDOR: Oracle Corporation https://java.oracle.com/
[11-07-2021 18:45:38][AP][DEBUG][Main] WORKING DIR: /Users/danielgroves/Documents/Downloads
[11-07-2021 18:45:38][AP][DEBUG][Main] SERVER FILE: /Users/danielgroves/Documents/Downloads/EssentialsXChat-2.19.0-dev+167-9bd35a2.jar
[11-07-2021 18:45:38][AP][INFO] | ------------------------------------------- |
[11-07-2021 18:45:38][AP][INFO] Thank you for installing AutoPlug!
[11-07-2021 18:45:38][AP][INFO] It seems like this is your first run and you haven't set your server key yet.
[11-07-2021 18:45:38][AP][INFO] For that, register yourself at https://autoplug.online/ and add a new server.
[11-07-2021 18:45:38][AP][INFO] Enter the key below:
[11-07-2021 18:45:43][AP][INFO] Authenticating server...
[11-07-2021 18:45:43][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] Connecting to AutoPlug-Web...
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] Handshake finished!
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] Connected to AutoPlug-Web successfully!
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] CipherSuite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] SessionId Session(1626047146024|TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] Authenticating server with Server-Key...
[11-07-2021 18:45:49][AP][DEBUG][SecuredConnection] [CON_TYPE: 0] PeerHost 144.91.78.158
[11-07-2021 18:45:52][AP][WARN] ================================
[11-07-2021 18:45:52][AP][WARN] Message: Connection issues!
[11-07-2021 18:45:52][AP][WARN] Details: [CON_TYPE: 0] Authentication failed (code:1): No matching server key found! Register your server at https://autoplug.online/ and get your server-key. Restart AutoPlug when done.
[11-07-2021 18:45:52][AP][WARN] Type: java.lang.Exception
[11-07-2021 18:45:52][AP][WARN] Stacktrace: 
[11-07-2021 18:45:52][AP][WARN] com.osiris.autoplug.client.network.online.SecuredConnection.<init>(SecuredConnection.java:81)
[11-07-2021 18:45:52][AP][WARN] com.osiris.autoplug.client.network.online.MainConnection.run(MainConnection.java:44)
[11-07-2021 18:45:52][AP][WARN] ================================
[11-07-2021 18:45:57][AP][DEBUG][TaskServerDownload] Downloading AutoPlug-Client.jar from: https://github.com/Osiris-Team/AutoPlug-Releases/raw/master/stable-builds/AutoPlug-Client.jar
[11-07-2021 18:46:10][AP][DEBUG][TaskServerDownload] Comparing hashes (SHA-256):
[11-07-2021 18:46:10][AP][DEBUG][TaskServerDownload] Input-Hash: 74f5a3adcc283a9293b3d3b37899d2d2f43b33147e228b2fd320d9f116397cbe
[11-07-2021 18:46:10][AP][DEBUG][TaskServerDownload] File-Hash: 74f5a3adcc283a9293b3d3b37899d2d2f43b33147e228b2fd320d9f116397cbe
[11-07-2021 18:46:10][AP][INFO] See you soon!
[11-07-2021 18:46:10][AP][DEBUG][AL] Stopped AP
[0m
```

**Comment by Osiris-Team** [comment]
@DannyDorito24 Cant you copy the console log directly (bc it contains more info)? Or does the screen session close?

**Comment by Osiris-Team** [comment]
@DannyDorito24 yeah just tried it out my self with screen and could achieve your error!

**Comment by Osiris-Team** [comment]
Ok just found out how to fix it.
It can be fixed by preventing the screen session from closing when the self-updater is installing the update.
This can be achieved by simply modifing your startup script to something like this:
`/usr/bin/screen -DmS AUTOPLUG%i sh -c 'java -jar AutoPlug-Client.jar; exec bash'`
For more details see this: https://unix.stackexchange.com/a/47279
